pugjs/pug

LICENSE

This reverts commit b62bc4605619fdc062a8e63845a3c1451f255d9f.
1. It's not 2015 here yet, though it soon will be.
2. TJ didn't do anything in 2015, so the copyright year would be wrong.
CC @hemanth

Revert "Updated License."

---

README.md

1. Use flat style
2. Use badge from shields.io for Gitter chat
According to http://shields.io (our badge provider), they are switching to a new default badge style:
> One of those two designs may become the default one. Vote by using them!
I am open for votes on the style of the badges:
- Flat style: [![Build Status](https://img.shields.io/travis/jadejs/jade/master.svg?style=flat)](https://travis-ci.org/jadejs/jade) [![Dependency Status](https://img.shields.io/gemnasium/jadejs/jade.svg?style=flat)](https://gemnasium.com/jadejs/jade) [![NPM version](https://img.shields.io/npm/v/jade.svg?style=flat)](http://badge.fury.io/js/jade) [![Join Gitter Chat](https://img.shields.io/badge/gitter-join%20chat%20%E2%86%92-brightgreen.svg?style=flat)](https://gitter.im/jadejs/jade?utm_source=badge&utm_med …

[VOTE] Better-looking badges

---

.gitignore
bin/jade.js
package.json
support/cov-combine.js
test/command-line.js

This PR can be understood to have two parts:
1. improve test coverage
2. allow tracking test coverage of bin/jade.js
For the first part, I have added tests for:
- `--obj` option of `bin/jade.js`
- reading from `stdin` and the `stdin()` function
- routines for prettifying the template name, i.e. the `replace()` call in `getNameFromFileName()`
For the second part I had to use some "hacks" and workarounds, because, unfortunately, istanbul is not as flexible as I would like it to be:
1. It does not support tracking JavaScript scripts spawned by `child_process.spawn()` or child_process.exec()`. Therefore, it is   necessary to execute separate istanbul instances for every command   spawned. This leads to the second problem:
2. Istanbul does not support "concatenating" or appending coverage …

Improve testing coverage for the Jade CLI application

---

bin/jade.js
test/command-line.js

This pull request contains 3 key changes:
1. This makes the CLI use synchronous code.  I very much doubt there is any real performance impact given that the jade rendering is the slow part and that was synchronous anyway.  It vastly simplifies the code, and in particular makes it way easier to do `--watch` mode.
2. It makes `--watch` mode use a `try/catch` block rather than `process.on('uncaughtException', ...)` (see the [node docs](http://nodejs.org/api/process.html#process_event_uncaughtexception) for why `process.on('uncaughtException', ...)` is a really bad idea here).
3. It adds a 1 second delay between each of the `--watch` tests.  This was necessary to get the tests passing on my mac (with or without the other two changes).  This is because the `mtime` of the files is only to the …

No process uncaught exception

---

package.json

This splits the coverage task out by adding “precoverage” and “postcoverage”.  It also deletes the intermediate coverage files once it is done.

Cleanup coverage

---

package.json

Running coverage report is never the point of `test`.
See also https://github.com/jadejs/jade/pull/1820#issuecomment-69693312.

Do not run coverage in `npm test`

---

lib/parser.js
test/cases/comments-in-case.html
test/cases/comments-in-case.jade

[fixes #1707]
This treats both buffered and unbuffered comments as unbuffered comments.  I don't think that matters though.

Add support for comments in a case block

---

lib/lexer.js

Lets disallow `:` without a space after it as part of the move to 2.0.0.  It would catch #1514 and also makes it easier to tell the difference between `:` and `:filter` when reading jade code (and parsing jade code).

Add warning for `:` not followed by a space

---

docs/views/api.jade
lib/index.js

[fixes #1705]
The name of the new API is fairly long and clunky, but it should only be used by build tools like jadeify.  I think this is therefore the simplest way to implement this.

Add `compileClientWithDependenciesTracked`

---

bin/jade.js
test/command-line.js

Problems that are fixed in the request:
1. #1086
2. problem, that when watching a folder jade-cli was not watching subtrees.
Solutions provided:
1. fetch dependencies from ```jade.compile```, and watch'em.
2. watch every file that is a target for render.
Improvement:
1. Unwatching a file, if the file was moved or removed.

Fixes for watch mode.

---

.travis.yml

Travis: test with io.js 1.1 instead of Node.js 0.11

---

docs/views/reference/attributes.jade
docs/views/reference/code.jade

- Fixes a typo in the documentation (sanatize ->  sanitize).

(docs) sanatize->sanitize

---

bin/jade.js
test/command-line.js

The option is to be enabled by default in Jade 2.0.0. Originally from Sean Ho (@seanho), further changes by me (@TimothyGu). From #1829.

Add an option to maintain directory hierarchy

---

docs/views/reference/interpolation.jade

Use possessive form of "its" rather than "it's". Removed an unnecessary (read: ungrammatical) comma from same paragraph.

Grammar fixes.

---

test/error.reporting.js

The error messages produced by v8 now included the variable name, so what before was
```
undefined is not a function
```
is now
```
foo is not a function
```
The test has been changed to reflect that.

updated tests to work with new version of v8

---

lib/compiler.js
lib/index.js
lib/runtime.js
test/unit.js

Details and code showing the leak: https://github.com/alubbe/memoryleak
In-browser demo: https://alubbe.github.io/memoryleak/
This leak has been bugging me since I updated node from 0.11.13 to 0.11.14. It has affected all my apps and causes them to take up over a gig of ram per process after a few days. Also, the constant GC makes the app slower and slower with each passing hour.
After forcing the processes to restart every day and also seeing the huge performance regression express received in the last Techempower benchmarks, I got fed up enough to go and track down the issue. First, I started to pre-compile the templates during the build step, and eval'ing the files' contents. This completely fixed any issues I had. So I started working on a new express middleware and just as I was …

fixed memory leak caused by compileDebug flag

---

lib/index.js

Building on the discussion in https://github.com/jadejs/jade/pull/1951, I would recommend to disable compileDebug by default for express' production env.
That's really all there is to it - what do you think?

disable compileDebug for express' production env

---

lib/lexer.js
test/jade.test.js

In the current version, pipeless text is not included in the line count used in error messages, which makes errors in pages rich with such text annoyingly difficult to track, e. g.:
p.
Lorem ipsum dolor sit amet, consectetur  
adipisicing elit, sed do eiusmod tempor 
incididunt ut labore et dolore magna aliqua. 
p.
Ut enim ad minim veniam, quis nostrud 
exercitation ullamco laboris nisi ut aliquip 
ex ea commodo consequat.
p.
Duis aute irure dolor in reprehenderit
in voluptate velit esse cillum dolore eu
fugiat nulla pariatur.
a(href="#" Next
returns a error message referring to line 4, while the error is really on line 13:
Jade:4
2|   Lorem ipsum dolor sit amet, consectetur  
3|   adipisicing elit, sed do eiusmod tempor 
> 4|   incididunt ut labore et dolore magna aliqua. 
5| p.
6|   Ut …

Better line number counting for pipeless text

---

.travis.yml

This way the Travis build outcome is not affected by Coveralls server downtime, which unfortunately is an issue.

travis: Use after_success for coverage report

---

docs/views/reference/code.jade

I know we don't want PRs for this, but my reason is to ask how to handle small doc updates like this.
Should I just re-run the script? Should I go directly into gh-pages and update manually?
Maybe we can write down our findings into a Contributing.md. I'm willing to get it started :)

fix documentation, see https://github.com/jadejs/jade/issues/1970

---

lib/compiler.js
lib/parser.js

(Part of https://github.com/jadejs/jade/issues/1975)
Found another weird bug in v8 - see jsperf http://jsperf.com/iterative-function-creation and v8 issue https://code.google.com/p/v8/issues/detail?id=4165
Anyhow, fixing it turns this
```
mixin-escape: 25284ms
mixin-no-escape: 17737ms
```
into
```
mixin-escape: 7463ms
mixin-no-escape: 2107ms
```
This PR assumes that all variables with names like ```jade_mixin_N``` are safe to use. If we don't want to make this assumption for the 1.x releases, we should bring it in 2.0. What do you think?

improve mixin performance by fixing https://code.google.com/p/v8/issues/detail?id=4165

---

lib/runtime.js

see https://github.com/jadejs/jade/issues/1975

improved speed of jade.escape()

---

register.js

This was driven by a desire to test client-side code compiled via [browserify](http://browserify.org/) using [mocha.js](http://mochajs.org/), which runs in `node` instead of the browser.  With `browserify`, it's easy to just require your template functions directly:
```js
var template = require('templates/kitten');  // a .jade template
```
and let a transform like [jadeify](https://www.npmjs.com/package/jadeify) do the heavy lifting for you.  Regular `node` complains, however, and when you attempt to require a template directly, it will (correctly) whine about not having a compiler for that file extension.
This PR adds a way to register `.jade` as a valid extension for require-able template functions, and was heavily inspired by [coffee-script/register](https://github.com/jashkenas/coffees …

Register .jade as a require-able file extension

---

test/cases/attrs.html
test/cases/attrs.jade

Add test cases for multiline attributes

---

package.json

`marked` and `uglify-js` have several reported security issues in versions used by jade:
- https://nodesecurity.io/advisories/module/marked
- https://nodesecurity.io/advisories/module/uglify-js

Update vulnerable dependencies

---

test/cases/some.styl

Stylus `@import` defaults to the directory of the source file.

Fix stylus import test

---

package.json

To include a fix (mishoo/UglifyJS2@63d35f8) for https://nodesecurity.io/advisories/48
Also filed jstransformers/jstransformer-uglify-js#6 to update that dependency.

Update uglify.js to 2.6.1

---

docs/views/reference/attributes.jade

In the **Class Attributes** part of the Language Reference, the anchor tag has a **Class Literal** attached. This, in addition to the second class attribute is making it so the element has **bing** as a class twice. Judging by the docs source, this is not the intended outcome as it shows only one **bing** class.
The `/docs` source shows the following:
```html
:htmlsrc
<a class="foo bar baz"></a><a class="foo bar baz bing"></a>
```
The generated html on the live site:
```html
<a class="foo bar baz"></a><a class="bing foo bar baz bing"></a>
```
**Note:** I wasn't able to get the CodeMirror working when following the contribution instructions found on #1927 so the html source wasn't being generated from the jade source which meant the html source was showing the hard coded value which was …

Class literal is duplicating the bing class

---

package.json

currently the package.json still refers to the jadejs org
This patch replaces it with the pugjs org

meta: update repo in package.json

---

docs/views/layout.jade

Right now jadejs/jade is a different person's repository (squatter maybe?). I changed Travis to pugjs as well, but coveralls gives me a 404 at pugjs/jade.

Change repo links to pugjs/jade

---

lib/index.js
package.json
test/pug.test.js
test/run.js

This will fix the fairly common issue where people add a custom filter
to one version of pug but then use a different version to do the
rendering (via something like a gulp/grunt plugin).

Accept filters as an option rather than defined on exports

---

README.md

...So you can't use Pug directly from your commandline shell without installing `pug-cli`.
This update is in response to GitHub issue #2295.

Note: Pug CLI has been split into a separate node module.

---

lib/index.js
package.json

By adding `.pug` directly to the path token, we ensure that it is still
recognised as an Include rather than a RawInclude.
Fixes #2308 and #2281

Fix including pug files with an implicit extension

---

lib/index.js
test/cases/auxiliary/extends-relative.pug
test/cases/include-extends-relative.html
test/cases/include-extends-relative.pug

Hello,
The [current test for `'.'` in the path](https://github.com/pugjs/pug/commit/433e2ab18b3aabe7b34947489f799c0390aa0ac4) excludes all paths with a `.` including `../`, breaking some relative paths.  I've written tests to demonstrate this case.  First I am pushing the tests which fail, then the fix which passes.
Thanks for your work!

use native path module to parse include/extends file extension

---

README.md

The Fusesource link is dead. :)
This is the new one:
https://scalate.github.io/scalate/documentation/scaml-reference.html

Fix broken Scala link

---

README.md

The pug php fork has been renamed from jade to pug

Jade.php renamed to Pug.php

---

README.md

Noticed that the README still mentions alpha when pug@2 is currently in beta. This updates the README to reflect that.

Correct README to use beta instead of alpha

---

lib/index.js

The 'else' block was not needed, thus it was removed. 'return null' after the conditionals.

'else' block removed from findReplacementFunc

---

README.md

I'd like to add my [laravel pug package](https://github.com/acidjazz/larpug) to the list of additional resources. I Finally got my tests to hit 100% coverage and I've been using this for long enough now to be happy w/ its stability.
Also its not a PHP re-write, it actually uses Pug :)

add larpug package to additional resources

---

lib/index.js

This is already implicitly done for the regular plugin path (`applyPlugins`).

Bind plugin function to plugin itself in findReplacementFunc()

---

lib/index.js
test/pug.test.js

Since there is not a `constructor` and thus a `constructor.name`
for detection this provides a name that can be used for the same
purpose. This is useful for application servers that allow the
template engine to be passed in.
I am working on PRs for other template engines for this as well.
It should also be noted that Handlebars, lodash, and underscore
are all detectable through this method already.
https://github.com/olado/doT/pull/216 is a PR for this in doT
ejs: https://github.com/mde/ejs/pull/220

Adds naming for detection of template engine

---

register.js

Since require.resolve returns back-slashed directories in Windows, when it gets added as a string within a string (like it does in register.js) those back-slahes become escapes. Since node is perfectly happy forward-slashed directories in Windows, I just converted them.

Fixed register.js to replace "\" with "/" for Windows.

---

package.json
packages/pug-filters/lib/handle-filters.js
packages/pug-filters/test/__snapshots__/per-filter-options-applied-to-nested-filters.test.js.snap
packages/pug-filters/test/per-filter-options-applied-to-nested-filters.test.js
scripts/filename-serializer.js

Original fix authored by @zah
This is a simple bug fix.
``` pug
script
:cdata-js:babel(presets=['es2015'])
const myFunc = () => `This is ES2015 in a CD${'ATA'}`;
```
When nested filters are used, the inner filter (babel) was failing to obtain its options from the `options.filterOptions.babel` table.

[pug-filters] Apply options to nested filters

---

packages/pug-linker/index.js

Change 'fat arrow' function into regular function syntax. This will
make it simpler for codebases to depend on pug if they are using older
versions of node.

Remove ES6 syntax from pug-linker

---

packages/pug-lexer/index.js
packages/pug/test/cases/attrs.colon.html
packages/pug/test/cases/attrs.colon.pug

* Add check for literal ‘:’
* Add test case for “typical” Vue.js short-cut syntax for `v-bind:`  (`:`)
* New test case passes with change (fails without the change)
Replaces #2713
Fixes #2454

[pug-lexer] Allow a colon to start an attribute

---

packages/pug-linker/index.js
packages/pug-linker/test/__snapshots__/index.test.js.snap
packages/pug/test/regression-2436/__snapshots__/index.test.js.snap
packages/pug/test/regression-2436/index.test.js
packages/pug/test/regression-2436/issue1.pug
packages/pug/test/regression-2436/issue2.pug
packages/pug/test/regression-2436/layout.pug
packages/pug/test/regression-2436/other1.pug
packages/pug/test/regression-2436/other2.pug
packages/pug/test/regression-2436/other_layout.pug

If an included template extends some other template, the named blocks should be removed once it has been linked.  This will stop those named blocks interfering with named blocks in the main template chain.
[fixes #2436]
[closes #2697]

Remove named blocks from included templates if they extend

---

.gitattributes
packages/pug-linker/index.js
packages/pug-linker/test/__snapshots__/index.test.js.snap
packages/pug/test/shadowed-block/__snapshots__/index.test.js.snap
packages/pug/test/shadowed-block/base.pug
packages/pug/test/shadowed-block/index.pug
packages/pug/test/shadowed-block/index.test.js
packages/pug/test/shadowed-block/layout.pug

Fixes #2774: "shadowed" blocks can be properly replaced / appended / prepended

---

packages/pug-code-gen/index.js
packages/pug/lib/index.js
packages/pug/test/__snapshots__/pug.test.js.snap
packages/pug/test/pug.test.js

Add compileFileModule method. This method is very useful for compiling templates to modules compatible with node js in order to make a require. In this way, we can save the content in a file for later use as a standalone module or asynchronous cache.

Add compileFileModule method

---

README.md

https://github.com/matannoam/pypugjs is a fork of the previously linked Python implementation. It appears to be more actively maintained.

Update README to change link to more recent Python implementation

---

packages/pug-parser/index.js

Some applications with older node fails due to strict not allowing 'const' or 'let' keywords.

replace const with var for use with 'strict'

---

packages/pug-parser/index.js
packages/pug-parser/test/__snapshots__/index.test.js.snap
packages/pug-parser/test/cases/text.tokens.json

Here, the following example will have a newline between `foo` and `bar`.
```pug
| foo
| bar
```
However, the following will not.
```pug
| foo
| #{bar}
```
This pull request fixes the behavior.
Should it also keep newline between text and code? For example,
```pug
| foo
= bar
```
This still won't have a newline.

Keep newline between text and interpolated-code

---

package.json

`uglify-js` is declared both as runtime and development dependency
This makes my install using `yarn install --production` to skip `uglify-js` from final bundle
This is actual for `jade@1.11.0`, `yarn@0.24.5` with `node@8.1.2`

Remove duplicate uglify-js dependency from devDependencies

---

packages/pug-parser/index.js

the "const" keyword is not supported in strict mode. ex. when the packages are downloaded on a remote machine with ~0.12 node version an error is thrown

unsupported keyword for production environments

---

packages/pug-lexer/index.js
packages/pug-lexer/test/__snapshots__/index.test.js.snap
packages/pug-lexer/test/cases/classes.pug

* Allow class names to begin with single dash, 0-9, a-z, and underscore
* Add test case that passes with change, fails without change
Fixes #2907

[pug-lexer] Relax class name requirements

---

packages/pug-lexer/index.js
packages/pug-lexer/test/__snapshots__/index.test.js.snap

Each attribute without value has `true` value by default. It should not be 'escaped' because it happens internally. But when we place attribute without a value at the beginning, we have a bug when `mustEscape` is set to `true`.
This PR prevents this behavior.
**Current**
```pug
div(first, second, third)
//- first  -> mustEscape: true
//- second -> mustEscape: false
//- third  -> mustEscape: false
```
**Next**
```pug
div(first, second, third)
//- first  -> mustEscape: false
//- second -> mustEscape: false
//- third  -> mustEscape: false
```

Don't ask escaping for boolean attributes at the beginning of attributes-list

---

.gitignore

After installing dependencies (npm@5.5.1) it automatically adds 'package-lock.json' file to each sub-project. I guess that we don't have lockfiles intentionally, so I asked git to ignore such files.
If that is not what we want, let's track lockfiles in git.

Ignore *lock file

---

.gitignore

This is continuation of https://github.com/pugjs/pug/pull/2955: adds yarn.lock file to .gitignore.

Ignore yarn.lock file

---

packages/pug-runtime/index.js
packages/pug-runtime/test/index.test.js
packages/pug/test/cases-es2015/attr.html
packages/pug/test/cases/styles.html
packages/pug/test/output-es2015/attr.html
packages/pug/test/pug.test.js

Related issue: #2961 
By only adding a semicolon when merging two style attributes, single style strings do not receive anymore a semicolon. 
I had to change the tests to reflect this new behavior

Trailing semicolon

---

packages/pug-filters/package.json

This is my first pull request (on a forked public repo at least), so please let me know if I'm missing anything.
None of the breaking changes in clean-css v4 should affect you, assuming this line in **run-filter.js** is the only place where you use it:
`result = new CleanCSS().minify(result).styles;`
This will close #2988.

Closes #2988 "Update clean-css dependency in pug-filters"

---

packages/pug-runtime/index.js
packages/pug-runtime/test/index.test.js

Overriding built-in method for `String` objects in test file turns `foo="boo"` result string into `foo="\"bar\""`.
Other primitive types are not so vulnerable to this so `String` prototype only is mangled.

[pug-runtime] toJSON method should be called on object-like values only. Fixes #2925

---

packages/pug/lib/index.js

Function preLex not called if template compile from string (See #3040)

Fix preLex fire support for plugins

---

README.md

Hi! 
I have started creating (and progressed quite well) a version of pug for a language called RPG (which runs on an IBM i & also works in C and COBOL) and was wondering if is allowed in the ports section?
https://github.com/WorksOfLiam/apug
Thanks for a great project!
Liam Barry

Include apug version in ports

---

packages/pug/package.json

I noticed that searching for "jade" on NPM does not show this module in the search results. It only shows up if you search via the exact name "pug".
This PR adds some keywords to the main module package.json to improve searchability. The order isn't meant to be a priority order. It's just sorted alphabetically to allow cleaner diffs in the future.

Add keywords to pug package.json

---

README.md
packages/pug-attrs/README.md
packages/pug-code-gen/README.md
packages/pug-error/README.md
packages/pug-filters/README.md
packages/pug-lexer/README.md
packages/pug-linker/README.md
packages/pug-load/README.md
packages/pug-parser/README.md
packages/pug-runtime/README.md
packages/pug-strip-comments/README.md
packages/pug-walk/README.md
packages/pug/README.md

For packages in a mono-repo,  david-dm.org requires a query parameter that identifies the location of the package.json.

Fix the dependency status badges in README.md of the child packages"

---

packages/pug-lexer/index.js
packages/pug-lexer/test/__snapshots__/index.test.js.snap
packages/pug-lexer/test/cases/attrs.js.pug

That is a tiny fix to have better supporting of spread operator in attributes.
For example the following case threw a SyntaxError:
```pug
div(anything ...props)
```
Now that works. It will help me to provide better experience for react users.

Allow spread operator in attributes

---

packages/pug-code-gen/index.js
packages/pug-lexer/index.js
packages/pug-lexer/test/check-lexer-functions.test.js
packages/pug-parser/index.js
packages/pug-walk/index.js

This PR adds support for iterating over maps and other iterable objects with the JS syntax `each var of map`. This example patches issue #3170. The syntax `each var of map` and `for var of map` has been introduced, but `each` and `for` can be used interchangeably, like with the original each syntax. 
All tests run and pass, but I haven't added any tests except for a small fix to recognise the `eachOf` function is the `pug-lexer`.
```js
var pug = require('pug');
var map = new Map([['foo', 'bar'], ['a', 'b']]);
var html = pug.renderFile('code.pug', { some_iterable: map });
console.log(html);
```
```
h1 Pug iteration test file
each el of some_iterable
p= el[0]
p= el[1]
```
```html
<h1>Pug iteration test file</h1><p>foo</p><p>bar</p><p>a</p><p>b</p>
```

Adding 'each .. of' syntax

---

packages/pug/test/eachOf/__snapshots__/index.test.js.snap
packages/pug/test/eachOf/error/left-side.pug
packages/pug/test/eachOf/error/no-brackets.pug
packages/pug/test/eachOf/error/one-val.pug
packages/pug/test/eachOf/error/right-side.pug
packages/pug/test/eachOf/index.test.js
packages/pug/test/eachOf/passing/brackets.pug
packages/pug/test/eachOf/passing/no-brackets.pug

This PR adds unit tests for the 'each .. of' syntax, added in #3179. 
It tests to ensure syntax like `each [key, value of map` does throw an error and that the intended usage does remain working. Two Jest snapshots have been added for the two tests that do output HTML.
The tests are located in `/packages/pug/tests/eachOf/`, but if there would be a better place for the tests I would be happy to move them to another folder.

Adding unit tests for 'each .. of'

---

packages/pug-load/README.md

There is a small typo in packages/pug-load/README.md.
Should read `overridden` rather than `overriden`.

docs: Fix simple typo, overriden -> overridden

---

packages/pug/lib/index.js

Hi! I'm trying to solve some issues in pug-loader, but in order to do that I need to forbid removing all unused mixins during the compilation. Instead of littering the "pug" interface with specific options, I decided that the better solution was allowing developers to override generateCode function. I believe that It might be useful in some other cases as well.

Add the possibility of replacing generateCode function

---

packages/pug-lexer/index.js
packages/pug-lexer/test/__snapshots__/index.test.js.snap

It now includes a description of what `each` should look like. We guide people towards the newer `each ... of ...` syntax, rather than the older `each ... in ...` syntax.

feat: improve error message for malformed each

---

package.json
packages/pug-lexer/package.json
yarn.lock

This means we pull in the current latest version of acorn, resulting in a single version everywhere, rather than multiple copies of acorn in this repo.

chore: update is-expression and jest

---

packages/pug-lexer/index.js
packages/pug-lexer/test/__snapshots__/index.test.js.snap
packages/pug-lexer/test/cases/interpolation.escape.pug

Pug-lexer always parsed escaped interpolations (`\#{...}` and `\!{...}`) into `#{...}`.
Here's the sample: https://runkit.com/shirohana/5f99255fb3cdb4001a711cf9
```js
const { Lexer } = require('pug-lexer')
const code = `
p \\#{value}
p \\!{value}
`
const lexer = new Lexer(code, { filename: 'index.pug' })
const tokens = lexer.getTokens()
```
```js
// Passed
assert(
tokens[2].val === '#{value}',
`1. expect "#{value}", actual: "${tokens[2].val}"`
)
// Throws
assert(
tokens[5].val === '!{value}',
`2. expect "!{value}", actual: "${tokens[5].val}"`
)
```

fix: Fix pug-lexer parsed escaped interpolations incorrectly

---

packages/pug-lexer/index.js
packages/pug/test/plugins.test.js

fix: keep lexer plugins inside tag interpolation

---

packages/pug-lexer/index.js
packages/pug-lexer/test/__snapshots__/index.test.js.snap
packages/pug-lexer/test/cases/each.else.pug

Variables starting with `of` cause the regex to "drift" on capture groups
```
each item of offers
i= item
```
This causes
```
The value variable for each must either be a valid identifier (e.g. `item`) or a
pair of identifiers in square brackets (e.g. `[key, value]`).
```
The non-greedy `(.*)` matches the `of` of the variable for the `of` statement. This causes matching group misalignment, which leads to the displayed error.
Rename your variable to something not starting with `of` :blush: 
---
fixes #3263
fixes #3275

fix capture groups for "each" statements

---

packages/pug-runtime/index.js
packages/pug-runtime/test/index.test.js
packages/pug/lib/index.js
packages/pug/test/__snapshots__/pug.test.js.snap
packages/pug/test/error.reporting.test.js
packages/pug/test/pug.test.js

When calling render/compile with `{ compileDebug: true }`, and an error was thrown from (or due to) a local, the `str` parameter in `pug_rethrow` was a `toJSON()`'d `Buffer`, and the rethrow code tried to `split` it like a string.
`str` would be something like:
```javascript
{
type: 'Buffer',
data: [ /* a bunch of numbers */ ]
}
```
which is what happens when you do something like `Buffer.from('foo').toJSON()`.
I couldn't really figure out where or how it happens, but I just made the rethrow function gracefully handle those serialized `Buffer` objects properly.
I wrote a test that failed (basically just calls an undefined function from an included file):
and then fixed it in this PR.

Properly handle errors originating from included files when compileDebug is enabled

---

packages/pug-lexer/index.js
packages/pug-lexer/package.json
yarn.lock

The updated dependency is written in TypeScript, which will help prepare us for converting pug-lexer to TypeScript

chore: update character-parser
