pugjs/pug

test/command-line.js
test/jade.test.js

This PR could really use some more eyes, especially for the watch mode test. I'm kind of anxious of all the child_process hackery/tricks as I'm not that proficient in Node.js.
See also #1795.

Some more tests

---

bin/jade.js

See https://github.com/jadejs/jade/commit/a49d63c3cd0aaec26fbd1a6d52947e84a9dc0e77#commitcomment-9253450

Clean up path and fs functions in CLI

---

History.md

I hope you have not written any payment checks

---

lib/index.js

Do not try to read a file if src string is defined

---

lib/parser.js

Fix error checking for mixin blocks in nested mixins

---

docs/views/api.jade

Add docs for jade.compileFileClient

---

docs/views/reference.jade
docs/views/reference/code.jade
docs/views/reference/interpolation.jade

As cool as this feature is, I feel like it needs it's own reference
page.
Aimed at #1620 and #1813.

Interpolation reference

---

bin/jade.js

Solution:
Wait for 200ms, and then check if the file exists.
And when the file is gone, unwatch it.

Fix for #1854

---

docs/views/reference/comments.jade

Hi, i fixed small typo in docs. If you want, you may merge this. Looking forward.

Fixed small typo

---

docs/stop.js

It was fixed in less-file 0.0.9.

docs/stop: Remove file query hack

---

bin/jade.js

Fixes #1906.
Also: do we need a test for this?

CLI: fix -H with watch mode

---

docs/views/reference/inheritance.jade

These sorts of things just always bug me. :)

Fix comma splice in inheritance doc

---

lib/runtime.js

porting https://github.com/jadejs/jade-runtime/commit/ed1ef32a2124cafee266066682e08daef98e7aec

cache character encoding function

---

lib/index.js
package.json

Fixes #1944, #1954.
See more discussion at jadejs/jade-parser#8 and jadejs/jade-lexer#7.

Use jade-strip-comments

---

test/cases/each.else.html
test/cases/each.else.jade

These syntaxes are non-standard and difficult to maintain.
See jadejs/jade-parser#11 and jadejs/jade-lexer#14.

Remove support for `- each` and `- else`

---

lib/index.js

No real advantages for now except consistency.

Use jade-runtime/wrap

---

docs/style/highlighting.less

Fixes font selection on Internet Explorer.

docs/style: Fix font-family syntax

---

test/anti-cases/self-closing-tag-with-block.jade
test/anti-cases/self-closing-tag-with-code.jade
test/anti-cases/self-closing.jade

Add additional test cases for self-closing tags with content

---

docs/client/index.js
docs/views/reference/attributes.jade

Document support for template strings in attributes 

---

docs/views/reference/filters.jade

Add instructions to install the jstransformer one needs

---

docs/views/reference/inheritance.jade

Additional context for `include pet` to avoid confusion for those that didn't figure out the variable scoping - like me :)

Documentation-Reference: Inheritance: 

---

docs/views/reference/iteration.jade

Add documentation for each-else syntax

---

package.json

To include the updated `uglify.js` dependency fix in `jstransformer-uglify-js` (jstransformers/jstransformer-uglify-js@e897c68)
Please also do a point release!

Update jstransformer-uglify-js dependency to 1.1.1

---

docs/views/reference/attributes.jade
docs/views/reference/mixins.jade

Cleaned up the documentation examples to standardize the optional commas.

Cleaned up commas in attributes

---

README.md

Changed the URLs to reflect the new repository at pugjs/jade rather than jadejs/jade.

Updated Travis and David-DM badges to new repository

---

package.json
test/cases/auxiliary/filter-in-include.pug
test/cases/filter-in-include.html
test/cases/filter-in-include.pug

Add test case for filter-in-include

---

lib/index.js
package.json

I forgot we already had #2171 we should figure out the best bits of
each approach.

Add plugins API

---

README.md

Intended to fix issue #2441 
Let me know if further adjustments are required.

update installation documentation to be more user-friendly

---

README.md
package.json

Update website URL

---

packages/pug/test/run-syntax-errors.test.js

I was not able to run the unit tests on my Windows machine. Turns out it was an easy fix.

Fix unit tests on Windows machines

---

packages/pug-filters/test/__snapshots__/index.test.js.snap
packages/pug/test/cases/filters.coffeescript.html
packages/pug/test/cases/filters.include.html
packages/pug/test/cases/filters.nested.html

coffee-script have released a new version with better output.  Our
tests show the old coffee-script output.

[chore] Update tests

---

package.json
packages/pug/test/__snapshots__/pug.test.js.snap
scripts/prettier-javascript-serializer.js

The output code generated by pug is pretty hideous.  Fortunately we can make our snapshots nice and readable using prettier and jest.

Use prettier for JavaScript snapshots

---

packages/pug-parser/index.js
packages/pug-parser/test/__snapshots__/index.test.js.snap
packages/pug-parser/test/__snapshots__/no-unnecessary-blocks.test.js.snap
packages/pug-parser/test/no-unnecessary-blocks.test.js
packages/pug/package.json
packages/pug/test/cases/text.html

This has a tiny effect on the output of the pretty printed mode, but
mostly it just simplifies rendering for third things like react-pug.

[pug-parser] Remove excess blocks

---

README.md

As requested here: https://github.com/AspNetMonsters/pugzor/issues/20

Added ASP.NET Core implementation to README

---

packages/pug-code-gen/index.js
packages/pug-filters/test/__snapshots__/filter-aliases.test.js.snap
packages/pug-filters/test/__snapshots__/per-filter-options-applied-to-nested-filters.test.js.snap
packages/pug-load/test/__snapshots__/index.test.js.snap
packages/pug-parser/README.md
packages/pug-parser/index.js
packages/pug-parser/test/__snapshots__/index.test.js.snap
packages/pug-parser/test/__snapshots__/no-unnecessary-blocks.test.js.snap
packages/pug-parser/try.js
packages/pug-walk/test/index.test.js

Add column field to ast nodes

---

README.md

With this the I've seen render times of less than 5ms whereas the normal cache I only get 20ms - 30ms.

added pug template cache to other

---

packages/pug-filters/lib/handle-filters.js
packages/pug-filters/test/__snapshots__/index.test.js.snap
packages/pug-filters/test/cases/filters.include.input.json
packages/pug-filters/test/index.test.js
packages/pug-filters/test/update-test-cases.js
packages/pug-lexer/test/__snapshots__/index.test.js.snap
packages/pug-lexer/test/cases/filters.include.pug
packages/pug-lexer/test/index.test.js
packages/pug-parser/test/__snapshots__/index.test.js.snap
packages/pug-parser/test/cases/filters.include.tokens.json
packages/pug-strip-comments/test/index.test.js
packages/pug/test/__snapshots__/pug.test.js.snap

fix include filters order applying, update test cases

fixes #2929, update test cases

---

README.md

Please merge to update the link to the current pypugjs repo.

new maintainer for pypugjs

---

README.md

Suggestions to add 2 packages to Additional resources / others:
- A package forked from jade-server, that works with pug files
- A pug-to-html package to create static websites

Add in additional resources of 2 packages

---

.travis.yml
lerna.json
package.json
packages/pug-filters/test/__snapshots__/filter-aliases.test.js.snap
packages/pug-filters/test/__snapshots__/index.test.js.snap
packages/pug-filters/test/__snapshots__/per-filter-options-applied-to-nested-filters.test.js.snap
packages/pug-lexer/test/__snapshots__/index.test.js.snap
packages/pug-linker/test/__snapshots__/index.test.js.snap
packages/pug-load/test/__snapshots__/index.test.js.snap
packages/pug-parser/test/__snapshots__/index.test.js.snap
packages/pug-parser/test/__snapshots__/no-unnecessary-blocks.test.js.snap
packages/pug-strip-comments/test/__snapshots__/index.test.js.snap
packages/pug/test/__snapshots__/pug.test.js.snap
packages/pug/test/duplicate-block/__snapshots__/index.test.js.snap
packages/pug/test/regression-2436/__snapshots__/index.test.js.snap
packages/pug/test/shadowed-block/__snapshots__/index.test.js.snap
yarn.lock

This updates the dev dependencies and adds Node.js 10 and 11 in the `.travis.yml`.

Update dev dependencies

---

packages/pug-code-gen/package.json

see: https://snyk.io/vuln/npm:constantinople:20180421

bump constantinople to 3.1.2

---

packages/pug-attrs/package.json
packages/pug-code-gen/package.json
packages/pug-error/package.json
packages/pug-filters/package.json
packages/pug-lexer/package.json
packages/pug-linker/package.json
packages/pug-load/package.json
packages/pug-parser/package.json
packages/pug-runtime/package.json
packages/pug-strip-comments/package.json
packages/pug-walk/package.json
packages/pug/package.json

Follow up to https://github.com/pugjs/pug/issues/3140#issuecomment-498305051

Update repo URLs in packages

---

packages/pug-lexer/index.d.ts

TypeScript definitions for pug-tokens

---

packages/pug-code-gen/package.json
yarn.lock

chore: update with

---

SECURITY.md

I did release a back-ported patch for today's vulnerability, but I don't intend to do so for future vulnerabilities. This updates the security policy to reflect that.

chore: update supported versions

---

README.md

docs: fix GitHub format
